### ISSUE TITLE
Can't Bypass Instagram Login

### ISSUE THREAD

**Issue by mushlih-almubarak** [noobpk/auto-change-tor-ip#4]
I tried to login to Instagram 10 times until it was blocked, then I used this tool to change the IP address so that it wasn't blocked, but I was still blocked by Instagram.

I tried using a VPN and I unblocked from Instagram login.

Why am I still blocked even though my IP has changed (with your tools)?

**Comment by noobpk** [comment]
You should be sure to add a sock proxy for your network or browser layer. Please check your public network address again later. I have no control over these ip addresses, so it may have been blacklisted by previous apps.
This tool can be used for many purposes and it depends on the user. This issue bypass is out of my scope.
