### ISSUE TITLE
error while trying to change ip 

### ISSUE THREAD

**Issue by RFHACKE** [noobpk/auto-change-tor-ip#5]
- [*] Change New IP
[01-05-22 15:09:16] [ERROR] - [x_x] Something went wrong, please check your error message.
 Message - maximum recursion depth exceeded while calling a Python object
[01-05-22 15:09:16] [INFO] - [*] Stop service tor
the script gives me this error.the number of loops was set to default and the timing was also default.please fix this

**Comment by noobpk** [comment]
> * [_] Change New IP
>   [01-05-22 15:09:16] [ERROR] - [x_x] Something went wrong, please check your error message.
>   Message - maximum recursion depth exceeded while calling a Python object
>   [01-05-22 15:09:16] [INFO] - [_] Stop service tor
>   the script gives me this error.the number of loops was set to default and the timing was also default.please fix this

You are already running on Kali Linux already installed on the Microsoft Store??

**Comment by noobpk** [comment]
Hi, you need to upgrade WSL 1 to 2 and convert your Subsystem Machine to WSL 2:
Ref: https://winaero.com/update-from-wsl-to-wsl-2-in-windows-10/

**Comment by noobpk** [comment]
Update: it seems the WSL version is not the main cause. Therefore, I would like to inform you that the Autorip currently does not support which Linux installed on the Microsoft store.
Thanks
