### ISSUE TITLE
import socks => ModuleNotFoundError: No module named 'socks'

### ISSUE THREAD

**Issue by luis-rivas-osanasalud** [noobpk/auto-change-tor-ip#7]
Hello @noobpk , thanks for sharing, I was following your instructions (I sow your video in youtube, also I cloned the repository) but unfortunately when I install the requirements and then try to run 'autorip.py' it throws me this error:

Traceback (most recent call last):
   File "autorip.py", line 5, in <module>
     import socks
ModuleNotFoundError: No module named 'socks'

Attached screen capture:

![consulta-NoobBoy](https://user-images.githubusercontent.com/88858665/189493651-f22bcc34-54d7-40e0-ae72-89ba448356c1.png)

I've been doing some research and still haven't been able to fix it even though other people have had something similar happen to them. Could you please give me some suggestion? (It is to determine if I have already taken it into account and applied it)

**Comment by noobpk** [comment]
Hi,
What is your OS ?
You can try install `python3 -m pip install SocksiPy_branch==1.01`

**Comment by luis-rivas-osanasalud** [comment]
Hello, I try manually too. But it doesn't  working. I'm working with Linuxmint as OS 

![image](https://user-images.githubusercontent.com/88858665/189528014-cb083a15-0e81-4aae-97ec-e6eefbf5490c.png)

Dependency is installed. Check the capture, do you have another suggestion? 

---
As a side note, I asked you the question with the company account instead of my personal account, that was an error, but I didn't have the option to delete the issue either.

**Comment by noobpk** [comment]
You can try uninstall and reinstall package, close and open your terminal and vscode. This issue not come from tool.

**Comment by luis-rivas-osanasalud** [comment]
Thank you very much for your answering, I have already tried all that without success

**Comment by geeks121** [comment]
Pysocks solved for this issue
please add Pysocks to
